name: MCF5
version: 1.0
description: Made by your one and only, _Savant...
main: me.mcf5.main.MCF5
commands:
  reset:
  delete:
  key:
  public:
  broadoff:
  votekick:
  refine:
  license:
  chat:
  forcecrate:
  cm: